name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make pull-latest
      - run: make all
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make push-commit

  test:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - run: make pull-latest
      - run: make test-adapters

  ssh:
    env:
      DOMAINNAME: degenfolio.degen.tax
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: test connection to server
        uses: ./ops/ssh-action/
        with:
          HOST: ubuntu@${{ env.DOMAINNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          CMD: 'echo "Successfully connected to $DOMAINNAME: `hostname`";'
