name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      CI_PROJECT_NAMESPACE: ${{ secrets.DOCKER_USER }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make pull-latest
      - run: make all
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make push-commit

  test:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - run: make pull-latest
      - run: make test-adapters
